name: libplacebo

on: [push, pull_request]

jobs:
  build:

    env:
      PLACEBO_DIR: placebo-dir

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Vulkan SDK
      run: |
        LUNAR_DEST_DIR=/etc/apt/sources.list.d/lunarg-vulkan-bionic.list
        LUNAR_LINK=http://packages.lunarg.com/vulkan/lunarg-vulkan-bionic.list
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc |
        sudo apt-key add -
        sudo wget -qO $LUNAR_DEST_DIR $LUNAR_LINK
        sudo apt update
        sudo apt install vulkan-sdk

    - name: Install Python3 packages
      env:
        PYTHON3_PKG: python3-setuptools python3-wheel
      run: |
        sudo apt-get install $PYTHON3_PKG

    - name: Install meson and ninja
      run: |
        sudo pip3 install meson ninja

    - name: Install sdl2
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev libsdl2-image-dev

    - name: Install shaderc libraries
      run: |
        LINK1=https://storage.googleapis.com/shaderc/artifacts/prod
        LINK2=graphics_shader_compiler/shaderc/linux/continuous_clang_release
        curl -LO $LINK1/$LINK2/255/20200124-124207/install.tgz
        tar -xvzf install.tgz
        mkdir -p $HOME/$PLACEBO_DIR
        cp -a install/lib/libshaderc*.a $HOME/$PLACEBO_DIR
        cp -a install/lib/libshaderc*.so* $HOME/$PLACEBO_DIR
        cp -a install/include/shaderc $HOME/$PLACEBO_DIR

    - name: Install libplacebo
      run: |
        git clone --depth 1 https://code.videolan.org/videolan/libplacebo.git
        cd libplacebo
        CFLAGS=-I$HOME/$PLACEBO_DIR LDFLAGS=-Wl,-L$HOME/$PLACEBO_DIR \
        meson build -Dprefix=$HOME/$PLACEBO_DIR --buildtype release
        ninja -C build
        ninja -C build install

    - name: Run tests
      env:
        PKG_PATH: lib/x86_64-linux-gnu/pkgconfig
      run: |
        export PKG_CONFIG_PATH=$HOME/$PLACEBO_DIR/$PKG_PATH:$PKG_CONFIG_PATH
        export LD_LIBRARY_PATH=$HOME/$PLACEBO_DIR:$LD_LIBRARY_PATH
        cargo test --all-features
